dist: trusty
group: edge
language: php
php:
    - 7.1
    - 7.2
    - 7.3
env:
    matrix:
        - MAGENTO_VERSION=2.3.5-p1
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.nvm
install:
    - composer global require hirak/prestissimo
    - composer require --dev magento/magento2-base:$MAGENTO_VERSION
script:
    - ./vendor/bin/phpunit  -c dev/tests/unit src/
